SMPL_SOURCES = \
smpl/pffft/pffft.c \
smpl/smpl_bitrate_controller.c \
smpl/smpl_celp.c \
smpl/smpl_calc_hp_coefs.c \
smpl/smpl_celp_util.c \
smpl/smpl_codec_util.c \
smpl/smpl_core_decoder.c \
smpl/smpl_core_encoder.c \
smpl/smpl_dec_api.c \
smpl/smpl_enc_api.c \
smpl/smpl_entropy_wrapper.c \
smpl/smpl_filt.c \
smpl/smpl_filt_allpass_fb.c \
smpl/smpl_get_signal_mode.c \
smpl/smpl_harm_postfilter.c \
smpl/smpl_harm_postfilter_util.c \
smpl/smpl_hb_gain_tables.c \
smpl/smpl_hb_lpc_tables.c \
smpl/smpl_helpers.c \
smpl/smpl_init_codec.c \
smpl/smpl_lpc.c \
smpl/smpl_lpc_util.c \
smpl/smpl_lsf_quant.c \
smpl/smpl_lsf_tables.c \
smpl/smpl_lsf_tables_st1.c \
smpl/smpl_lsf_tables_st2.c \
smpl/smpl_lsf_wrapper.c \
smpl/smpl_nrgres_tables.c \
smpl/smpl_param_coding.c \
smpl/smpl_perc_wght.c \
smpl/smpl_pitch.c \
smpl/smpl_pitch_tables.c \
smpl/smpl_pitch_util.c \
smpl/smpl_plc.c \
smpl/smpl_postfilter.c \
smpl/smpl_postfilter_util.c \
smpl/smpl_pulse_coding.c \
smpl/smpl_pulse_coding_util.c \
smpl/smpl_pulse_tables.c \
smpl/smpl_quant_nrg_res.c \
smpl/smpl_resampler_wrapper.c \
smpl/smpl_tables.c \
smpl/smpl_typedef.c \
smpl/smpl_vad.c \
smpl/smpl_vad_wrapper.c \
smpl/smpl_bandwidth_extension.c \
smpl/opus_smpl_decode.c \
smpl/opus_smpl_encode.c \
smpl/opus_smpl_repacketizer.c

SMPL_SOURCES_FAST_MATH = \
smpl/smpl_celp_util.c \
smpl/smpl_codec_util.c \
smpl/smpl_get_signal_mode.c \
smpl/smpl_filt.c \
smpl/smpl_harm_postfilter_util.c \
smpl/smpl_lpc_util.c \
smpl/smpl_pitch_util.c \
smpl/smpl_postfilter_util.c

SMPL_SOURCES_OPTIMIZE_SIZE = \
smpl/pffft/pffft.c \
smpl/smpl_bandwidth_extension.c \
smpl/smpl_bitrate_controller.c \
smpl/smpl_calc_hp_coefs.c \
smpl/smpl_celp.c \
smpl/smpl_core_encoder.c \
smpl/smpl_core_decoder.c \
smpl/smpl_enc_api.c \
smpl/smpl_filt_allpass_fb.c \
smpl/smpl_harm_postfilter.c \
smpl/smpl_hb_lpc_tables.c \
smpl/smpl_helpers.c \
smpl/opus_smpl_encode.c \
smpl/smpl_init_codec.c \
smpl/smpl_lpc.c \
smpl/smpl_lsf_quant.c \
smpl/smpl_lsf_tables.c \
smpl/smpl_lsf_tables_st1.c \
smpl/smpl_lsf_tables_st2.c \
smpl/smpl_nrgres_tables.c \
smpl/smpl_perc_wght.c \
smpl/smpl_pitch.c \
smpl/smpl_pitch_tables.c \
smpl/smpl_postfilter.c \
smpl/smpl_pulse_tables.c \
smpl/smpl_plc.c \
smpl/smpl_quant_nrg_res.c \
smpl/opus_smpl_repacketizer.c \
smpl/smpl_tables.c \
smpl/smpl_vad.c \
smpl/smpl_vad_wrapper.c \
