# Temporar. All tables can be autogenerated during Init
#include("../../includes.jl")

function blocktrack_encode(blocktrack)
    @assert(length(blocktrack) == 8 || length(blocktrack) == 4)
    bits_per_sf = 4
    test = all(blocktrack.-1 .< 2^bits_per_sf-1)
    @assert(test)
    @assert(all(blocktrack.-1 .>= 0))  
    enc = UInt32(0) 
    for i = 1:length(blocktrack)-1
        enc = enc + (blocktrack[i]-1)
        enc = enc * 2^bits_per_sf
    end
    enc = enc + (blocktrack[end]-1)
    return enc 
end

function blockseg_encode_ec(ec_enc, blockseg)
    # 2 bits for block 1 - 3
    # 1 bit for seglen 1 - 2
    @assert(length(blockseg) <= 6)    
    ec_encode_uniform(ec_enc, length(blockseg)-1, 6)
    for i = 1:length(blockseg)
        @assert(blockseg[i][1] > 0)
        @assert(blockseg[i][1] <= 9)
        ec_encode_uniform(ec_enc, blockseg[i][1]-1, 9)
        @assert(blockseg[i][2] > 0)
        @assert(blockseg[i][2] <= 4) 
        ec_encode_uniform(ec_enc, blockseg[i][2]-1, 4)
    end
end

function blockseg_encode(blockseg)
    bits_per_val = 4
    enc = UInt64(0)
    #if length(blockseg) == 5
    #println(length(blockseg)) 
    #end
    for i = 1:length(blockseg)-1
        enc = enc + (blockseg[i][1]-1)
        enc = enc * 2^bits_per_val
        enc = enc + (blockseg[i][2]-1)
        enc = enc * 2^bits_per_val        
    end
    enc = enc + (blockseg[end][1]-1)
    enc = enc * 2^bits_per_val
    enc = enc + (blockseg[end][2]-1)    
    enc *= 2^(2 * bits_per_val * (8-length(blockseg)))
    return enc
end

function generate_blocksegs_data(pitch_struct)
    block_seg_start = 0
    block_seg_ix = zeros(Int,2, length(pitch_struct.blocktracks))
    enc_blocksegs = UInt64[]
    blocksegs2idx = UInt8[]
    tot_len_blocksegs = 0
    ec_enc = create_ec_encoder(1024)
    for i = 1:length(pitch_struct.blocktracks)
        blocksegs = pitch_struct.track2blocksegs[pitch_struct.blocktracks[i]]
        num_blocksegs = length(blocksegs)
        for j = 1 : length(blocksegs)
            tot_len_blocksegs += length(blocksegs[j])
            append!(enc_blocksegs, blockseg_encode(blocksegs[j]))
            append!(blocksegs2idx, pitch_struct.blocksegs2idx[blocksegs[j]])
            blockseg_encode_ec(ec_enc, blocksegs[j])
        end
        block_seg_ix[1, i] = block_seg_start
        block_seg_ix[2, i] = num_blocksegs
        block_seg_start += num_blocksegs
    end
    payload = ec_enc_done(ec_enc)
    c_enc = free(ec_enc)
    println(length(payload))
    println("tot_len_blocksegs: $tot_len_blocksegs length(enc_blocksegs): $(length(enc_blocksegs))")
    return block_seg_ix, enc_blocksegs, payload, blocksegs2idx
end

#@printf("enc = %x \n", blocktrack_encode(pitch_struct.blocktracks[10]))
 
cfg = config(16000)
pitch_struct = create_pitch_struct(cfg)

pitch_struct_10 = create_pitch_struct(config(16000; packet_ms=10))

enc_blocktracks = [blocktrack_encode(block) for block in pitch_struct.blocktracks]
enc_blocktracks_10 = [blocktrack_encode(block) for block in pitch_struct_10.blocktracks]

# block_seg_start = 0
# block_seg_ix = zeros(Int,2, length(pitch_struct.blocktracks))
# enc_blocksegs = UInt64[]
# blocksegs2idx = UInt8[]
# for i = 1:length(pitch_struct.blocktracks)
#     blocksegs = pitch_struct.track2blocksegs[pitch_struct.blocktracks[i]]
#     num_blocksegs = length(blocksegs)
#     for j = 1 : length(blocksegs)
#         append!(enc_blocksegs, blockseg_encode(blocksegs[j]))
#         append!(blocksegs2idx, pitch_struct.blocksegs2idx[blocksegs[j]])
#     end
#     block_seg_ix[1, i] = block_seg_start
#     block_seg_ix[2, i] = num_blocksegs
#     global block_seg_start += num_blocksegs
# end
block_seg_ix, enc_blocksegs, payload, blocksegs2idx = generate_blocksegs_data(pitch_struct)
block_seg_ix_10, enc_blocksegs_10, payload_10, blocksegs2idx_10 = generate_blocksegs_data(pitch_struct_10)

lags_CB = lags_CBs[20]

io = open(string(@__DIR__, "/smpl_pitch_tables.h"),"w")
print(io, "#include <stdint.h> \n")
print(io, "#include \"smpl_defines.h\" \n\n")
print(io, "#ifdef __cplusplus\n")
print(io, """extern "C" {\n""")
print(io, "#endif\n")
print(io, "#define PITCH_NUM_BLOCKS (SMPL_MAXPITCH_MS - SMPL_MINPITCH_MS)/SMPL_PITCHBLOCK_MS \n")
print(io, "#define NUM_BLOCKTRACKS", " ",length(pitch_struct.blocktracks), "\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs_ix[NUM_BLOCKTRACKS][2];\n")
print(io, "#define NUM_BLOCKTRACKS_10", " ",length(pitch_struct_10.blocktracks), "\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs_ix_10[NUM_BLOCKTRACKS_10][2];\n")
print(io, "#define NUM_BLOCKSEGS", " ",length(enc_blocksegs), "\n")
print(io, "#define NUM_BLOCKSEGS_BYTES", " ",length(payload), "\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs[NUM_BLOCKSEGS_BYTES];\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs2idx[NUM_BLOCKSEGS];\n")
print(io, "extern const uint8_t smpl_pitch_firstblock_range[PITCH_NUM_BLOCKS][2];\n")
print(io, "extern const uint8_t smpl_pitch_blockseg_idx_DCMF_20[NUM_BLOCKSEGS];\n")

print(io, "#define NUM_BLOCKSEGS_10", " ",length(enc_blocksegs_10), "\n")
print(io, "#define NUM_BLOCKSEGS_10_BYTES", " ",length(payload_10), "\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs_10[NUM_BLOCKSEGS_10_BYTES];\n")
print(io, "extern const uint8_t smpl_pitch_blocksegs2idx_10[NUM_BLOCKSEGS_10];\n")
print(io, "extern const uint8_t smpl_pitch_firstblock_range_10[PITCH_NUM_BLOCKS][2];\n")
print(io, "extern const uint8_t smpl_pitch_blockseg_idx_DCMF_10[NUM_BLOCKSEGS_10];\n")

print(io, "extern const uint8_t smpl_pitch_block_transition_DCMF_20[PITCH_NUM_BLOCKS][PITCH_NUM_BLOCKS];\n")
print(io, "extern const int16_t smpl_pitch_acbgain_thr_10_Q14[2];\n")
print(io, "extern const int16_t smpl_pitch_acbgain_thr_20_Q14[2];\n")

print(io, "#define N_DELTALAG_CMFS", " ", length(lags_CBs_packed[20].delta_lag_dcmfs), "\n")
print(io, "#define LEN_DELTALAG_CMF", " ", length(lags_CBs_packed[20].delta_lag_dcmfs[1])+1, "\n")
print(io, "extern const uint8_t smpl_pitch_delta_lag_DCMFs[N_DELTALAG_CMFS][LEN_DELTALAG_CMF-1];\n")
print(io, "#ifdef __cplusplus\n")
print(io, "}\n")
print(io, "#endif\n")
close(io)

io = open(string(@__DIR__, "/smpl_pitch_tables.c"),"w")
print(io, "#include \"smpl_pitch_tables.h\" \n\n")

print(io, "const uint8_t smpl_pitch_blocksegs[NUM_BLOCKSEGS_BYTES] = {\n   ")
N = length(payload) ÷ 16
rem = length(payload) - N * 16
for n = 1 : N
    for j = 1 : 16  
        print(io, payload[j + (n-1)*16],"u, ")
    end
    print(io, "\n   ")
end
for j = 1 : rem-1    
    print(io, payload[N*16 + j],"u, ")
end
print(io, payload[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_blocksegs_10[NUM_BLOCKSEGS_10_BYTES] = {\n   ")
N = length(payload_10) ÷ 16
rem = length(payload_10) - N * 16
for n = 1 : N
    for j = 1 : 16    
        print(io, payload_10[j + (n-1)*16],"u, ")
    end
    print(io, "\n   ")
end
for j = 1 : rem-1    
    print(io, payload_10[N*16 + j],"u, ")
end
print(io, payload_10[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_blocksegs2idx[NUM_BLOCKSEGS] = {\n   ")
for j = 1 : length(blocksegs2idx)-1    
    print(io, blocksegs2idx[j],"u, ")
end
print(io, blocksegs2idx[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_blocksegs2idx_10[NUM_BLOCKSEGS_10] = {\n   ")
for j = 1 : length(blocksegs2idx_10)-1    
    print(io, blocksegs2idx_10[j],"u, ")
end
print(io, blocksegs2idx_10[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_blocksegs_ix[NUM_BLOCKTRACKS][2] = {\n    ")
for j = 1 : size(block_seg_ix)[2]-1    
    print(io, "{", block_seg_ix[1, j],"u,", block_seg_ix[2, j],"u}, ")
end
print(io, "{", block_seg_ix[1, end],"u,", block_seg_ix[2, end], "u}\n}; \n")

print(io, "const uint8_t smpl_pitch_blocksegs_ix_10[NUM_BLOCKTRACKS_10][2] = {\n    ")
for j = 1 : size(block_seg_ix_10)[2]-1    
    print(io, "{", block_seg_ix_10[1, j],"u,", block_seg_ix_10[2, j],"u}, ")
end
print(io, "{", block_seg_ix_10[1, end],"u,", block_seg_ix_10[2, end], "u}\n}; \n")

print(io, "const uint8_t smpl_pitch_firstblock_range[PITCH_NUM_BLOCKS][2] = {\n    ")
for j = 1 : length(pitch_struct.firstblock_range)-1    
    print(io, "{", pitch_struct.firstblock_range[j][1]-1,"u,", pitch_struct.firstblock_range[j][2]-1,"u}, ")
end
print(io, "{", pitch_struct.firstblock_range[end][1]-1,"u,", pitch_struct.firstblock_range[end][2]-1, "u}\n}; \n")

print(io, "const uint8_t smpl_pitch_firstblock_range_10[PITCH_NUM_BLOCKS][2] = {\n    ")
for j = 1 : length(pitch_struct_10.firstblock_range)-1    
    print(io, "{", pitch_struct_10.firstblock_range[j][1]-1,"u,", pitch_struct_10.firstblock_range[j][2]-1,"u}, ")
end
print(io, "{", pitch_struct_10.firstblock_range[end][1]-1,"u,", pitch_struct_10.firstblock_range[end][2]-1, "u}\n}; \n")

print(io, "const uint8_t smpl_pitch_blockseg_idx_DCMF_20[NUM_BLOCKSEGS] = {\n    ")
for j = 1 : length(lags_CBs_packed[20].blockseg_idx_dcmf)-1    
    print(io, lags_CBs_packed[20].blockseg_idx_dcmf[j],"u, ")
end
print(io, lags_CBs_packed[20].blockseg_idx_dcmf[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_blockseg_idx_DCMF_10[NUM_BLOCKSEGS_10] = {\n    ")
for j = 1 : length(lags_CBs_packed[10].blockseg_idx_dcmf)-1    
    print(io, lags_CBs_packed[10].blockseg_idx_dcmf[j],"u, ")
end
print(io, lags_CBs_packed[10].blockseg_idx_dcmf[end],"u\n}; \n")

print(io, "const uint8_t smpl_pitch_block_transition_DCMF_20[PITCH_NUM_BLOCKS][PITCH_NUM_BLOCKS] = {\n    ")
for j = 1 : size(lags_CBs_packed[20].block_transition_dcmf)[2]-1
    print(io, "{")
    for i = 1 : size(lags_CBs_packed[20].block_transition_dcmf)[1]-1    
        print(io, lags_CBs_packed[20].block_transition_dcmf[i, j],"u, ")
    end
    print(io, lags_CBs_packed[20].block_transition_dcmf[end, j],"u }, \n    ")
end
print(io, "{")
for i = 1 : size(lags_CBs_packed[20].block_transition_dcmf)[1]-1    
    print(io, lags_CBs_packed[20].block_transition_dcmf[i, end],"u, ")
end
print(io, lags_CBs_packed[20].block_transition_dcmf[end, end],"u }\n}; \n")

for fl = [10, 20]
    print(io, "const int16_t smpl_pitch_acbgain_thr_$(fl)_Q14[2] = {$(Int16(round(2^14*lags_CBs[fl].acbgain_thr[1]))), $(Int16(round(2^14*lags_CBs[fl].acbgain_thr[2]))) }; \n\n")
end

fl = 20
print(io, "const uint8_t smpl_pitch_delta_lag_DCMFs[N_DELTALAG_CMFS][LEN_DELTALAG_CMF-1] = {\n    ")
for j = 1 : length(lags_CBs_packed[fl].delta_lag_dcmfs)-1
    print(io, "{")
    for i = 1 : length(lags_CBs_packed[fl].delta_lag_dcmfs[j])-1    
        print(io, lags_CBs_packed[fl].delta_lag_dcmfs[j][i],"u, ")
    end
    print(io, lags_CBs_packed[fl].delta_lag_dcmfs[j][end],"u }, \n    ")
end
print(io, "{")
for i = 1 : length(lags_CBs_packed[fl].delta_lag_dcmfs[end])-1   
    print(io, lags_CBs_packed[fl].delta_lag_dcmfs[end][i],"u, ")
end
print(io, lags_CBs_packed[fl].delta_lag_dcmfs[end][end],"u }\n}; \n")
close(io)
