#!/usr/bin/env python3
"""
GPU-accelerated parameter sweep for TLCS codec.

Patches tlcs_tune.h with each parameter combination, rebuilds the codec,
encodes/decodes all speech files, scores with NISQA on GPU, reports best.

Usage:
    python3 tools/gpu_sweep.py --corpus ~/corpus/speech/ --bitrate 9600
"""
import argparse
import itertools
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import numpy as np
import torch
import soundfile as sf
import torchaudio.functional as AF
from torchmetrics.audio.nisqa import NonIntrusiveSpeechQualityAssessment

# ── Parameter grid ──────────────────────────────────────────────
PARAM_GRID = {
    "TUNE_ALFE_BOOST":       [1.0, 1.2, 1.4, 1.6, 1.8],
    "TUNE_SBR_BASE_MULT":    [0.5, 0.7, 0.9],
    "TUNE_SBR_DEPTH_FRAC":   [0.5, 0.667, 0.8],
    "TUNE_NF_CODED":         [0.05, 0.10, 0.15],
    "TUNE_NF_UNCODED_HI":    [0.4, 0.6, 0.8],
    "TUNE_NF_UNCODED_SLOPE": [0.30, 0.45, 0.55],
    "TUNE_PF_NUM_LR":        [0.55, 0.65, 0.75],
    "TUNE_PF_DEN_LR":        [0.75, 0.80, 0.85],
    "TUNE_PF_TILT_LR":       [0.20, 0.30, 0.40],
}

DEFAULTS = {
    "TUNE_ALFE_BOOST": 1.4,
    "TUNE_SBR_BASE_MULT": 0.7,
    "TUNE_SBR_DEPTH_FRAC": 0.667,
    "TUNE_NF_CODED": 0.10,
    "TUNE_NF_UNCODED_HI": 0.60,
    "TUNE_NF_UNCODED_SLOPE": 0.45,
    "TUNE_PF_NUM_LR": 0.65,
    "TUNE_PF_DEN_LR": 0.80,
    "TUNE_PF_TILT_LR": 0.30,
}

PROJECT_DIR = Path(__file__).resolve().parent.parent
TUNE_H = PROJECT_DIR / "src" / "codec" / "tlcs_tune.h"
BUILD_DIR = PROJECT_DIR / "build"
ENC_BIN = BUILD_DIR / "tools" / "tlcs_enc"
DEC_BIN = BUILD_DIR / "tools" / "tlcs_dec"


def write_tune_h(params: dict):
    """Write tlcs_tune.h with the given parameter values."""
    lines = [
        "/* Auto-generated by gpu_sweep.py */",
        "#ifndef TLCS_TUNE_H",
        "#define TLCS_TUNE_H",
        "",
    ]
    for name, val in params.items():
        lines.append(f"#define {name:<25s} {val:.4f}f")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    TUNE_H.write_text("\n".join(lines))


def build_codec():
    """Rebuild the codec. Returns True on success."""
    r = subprocess.run(
        ["cmake", "--build", str(BUILD_DIR), "--", "-j8"],
        capture_output=True, timeout=30,
    )
    return r.returncode == 0


def encode_decode_all(wav_files, bitrate, tmp_dir):
    """Encode and decode all files. Returns list of decoded paths."""
    decoded = []
    for wav in wav_files:
        stem = Path(wav).stem
        enc_path = os.path.join(tmp_dir, f"{stem}.tlcs")
        dec_path = os.path.join(tmp_dir, f"{stem}_dec.wav")
        r1 = subprocess.run(
            [str(ENC_BIN), wav, enc_path, str(bitrate)],
            capture_output=True, timeout=10,
        )
        if r1.returncode != 0:
            return None
        r2 = subprocess.run(
            [str(DEC_BIN), enc_path, dec_path],
            capture_output=True, timeout=10,
        )
        if r2.returncode != 0:
            return None
        decoded.append(dec_path)
    return decoded


def score_batch_nisqa(nisqa_model, wav_paths):
    """Score a batch of wav files with NISQA. Returns list of MOS floats."""
    scores = []
    for p in wav_paths:
        audio, sr = sf.read(p, dtype='float32')
        if audio.ndim > 1:
            audio = audio[:, 0]
        t = torch.tensor(audio)
        if sr != 16000:
            t = AF.resample(t, sr, 16000)
        nisqa_model.update(t.unsqueeze(0))
        result = nisqa_model.compute()
        nisqa_model.reset()
        scores.append(float(result[0].item()))
    return scores


def one_at_a_time_sweep(wav_files, bitrate, nisqa_model, baseline_score):
    """Sweep one parameter at a time, keeping others at default."""
    best_params = dict(DEFAULTS)
    best_score = baseline_score

    for param_name, values in PARAM_GRID.items():
        print(f"\n--- Sweeping {param_name} ({len(values)} values) ---")
        param_best_val = best_params[param_name]
        param_best_score = best_score

        for val in values:
            trial = dict(best_params)
            trial[param_name] = val

            write_tune_h(trial)
            if not build_codec():
                print(f"  {param_name}={val:.3f}: BUILD FAILED")
                continue

            with tempfile.TemporaryDirectory() as tmp:
                decoded = encode_decode_all(wav_files, bitrate, tmp)
                if decoded is None:
                    print(f"  {param_name}={val:.3f}: ENCODE/DECODE FAILED")
                    continue
                scores = score_batch_nisqa(nisqa_model, decoded)

            mean_score = np.mean(scores)
            marker = " ***" if mean_score > param_best_score else ""
            print(f"  {param_name}={val:.3f}: NISQA={mean_score:.3f}{marker}")

            if mean_score > param_best_score:
                param_best_score = mean_score
                param_best_val = val

        best_params[param_name] = param_best_val
        best_score = param_best_score
        print(f"  BEST: {param_name}={param_best_val:.3f} (NISQA={param_best_score:.3f})")

    return best_params, best_score


def main():
    parser = argparse.ArgumentParser(description="GPU-accelerated TLCS parameter sweep")
    parser.add_argument("--corpus", required=True, help="Directory with .wav files")
    parser.add_argument("--bitrate", type=int, default=9600)
    parser.add_argument("--max_files", type=int, default=20)
    args = parser.parse_args()

    # Find wav files
    wav_files = sorted(str(p) for p in Path(args.corpus).rglob("*.wav"))[:args.max_files]
    if not wav_files:
        print(f"No wav files in {args.corpus}")
        sys.exit(1)
    print(f"Using {len(wav_files)} wav files at {args.bitrate} bps")

    # Init NISQA
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"NISQA device: {device}")
    nisqa = NonIntrusiveSpeechQualityAssessment(16000).to(device)
    nisqa.eval()

    # Configure cmake if needed
    if not BUILD_DIR.exists():
        subprocess.run(["cmake", "-B", str(BUILD_DIR), str(PROJECT_DIR)], check=True)

    # Baseline with current defaults
    print("\n=== Baseline (current params) ===")
    write_tune_h(DEFAULTS)
    assert build_codec(), "Baseline build failed"

    with tempfile.TemporaryDirectory() as tmp:
        decoded = encode_decode_all(wav_files, args.bitrate, tmp)
        assert decoded, "Baseline encode/decode failed"
        baseline_scores = score_batch_nisqa(nisqa, decoded)

    baseline_mean = np.mean(baseline_scores)
    print(f"Baseline NISQA: {baseline_mean:.3f} ± {np.std(baseline_scores):.3f}")

    # Run sweep
    print("\n=== One-at-a-time parameter sweep ===")
    t0 = time.time()
    best_params, best_score = one_at_a_time_sweep(
        wav_files, args.bitrate, nisqa, baseline_mean
    )
    elapsed = time.time() - t0

    # Apply best params
    write_tune_h(best_params)
    build_codec()

    print(f"\n{'='*60}")
    print(f"SWEEP COMPLETE in {elapsed/60:.1f} minutes")
    print(f"{'='*60}")
    print(f"Baseline NISQA: {baseline_mean:.3f}")
    print(f"Best NISQA:     {best_score:.3f} ({best_score - baseline_mean:+.3f})")
    print(f"\nBest parameters:")
    for k, v in best_params.items():
        changed = " (changed)" if v != DEFAULTS[k] else ""
        print(f"  {k}: {v:.4f}{changed}")

    # Save results
    results = {
        "baseline_nisqa": baseline_mean,
        "best_nisqa": best_score,
        "delta": best_score - baseline_mean,
        "best_params": best_params,
        "defaults": DEFAULTS,
        "bitrate": args.bitrate,
        "num_files": len(wav_files),
        "elapsed_minutes": elapsed / 60,
    }
    results_path = PROJECT_DIR / "tools" / "sweep_results.json"
    with open(results_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\nResults saved to {results_path}")


if __name__ == "__main__":
    main()
